[project]
name = "pipeline-rag-assistant"
version = "0.1.0"
description = "Pipelines Runbook Agent"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain[openai]>=0.3.27",
    "langgraph>=0.6.5",
    "python-dotenv>=1.1.1",
    "ruff>=0.12.9",
]
